# Generated by Django 5.1.6 on 2025-03-03 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_b2b_partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='B2CUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('PAID', 'Paid'), ('NOT_PAID', 'Not Paid'), ('REJECTED', 'Rejected')], default='IN_PROCESS', max_length=255)),
                ('percentage', models.FloatField()),
                ('amount', models.FloatField()),
                ('b2b_receipent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_system.b2bpartner')),
                ('b2c_receipent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_system.b2cuser')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='referral_system.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B2B_PARTNER', 'B2B Partner'), ('B2C_USER', 'B2C user')], max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('b2b_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='referral_system.b2bpartner')),
                ('b2c_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='referral_system.b2cuser')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='referral_system.referralcode'),
        ),
    ]
