# Generated by Django 5.1.6 on 2025-03-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0002_commission_date_converted_lead_date_referred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='referral_system.lead'),
        ),
    ]
