# Generated by Django 5.1.6 on 2025-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0003_alter_commission_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2b_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('b2c_commission_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Commission Settings',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
    ]
