# Generated by Django 5.1.6 on 2025-03-06 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0004_commissionpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_converted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_referred',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
