# Generated by Django 4.2.3 on 2025-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bpartner',
            name='image_link',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
