# Generated by Django 5.1.6 on 2025-03-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalDocuments',
        ),
    ]
