# Generated by Django 5.1.6 on 2025-03-07 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0002_delete_medicaldocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='care_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CARE_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
