# Generated by Django 5.1.7 on 2025-04-05 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0005_googlefittoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-defined device name (e.g., John's Watch)", max_length=50)),
                ('device_code', models.CharField(help_text='Device ID (e.g., AK_00003)', max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_onboarding.userdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'user_id'], name='user_onboar_device__c967d4_idx'), models.Index(fields=['status'], name='user_onboar_status_637354_idx')],
                'unique_together': {('device_id', 'user_id', 'created_at')},
            },
        ),
    ]
