# Generated by Django 5.1.6 on 2025-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0007_patient_profile_picture_alter_patient_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestyledetails',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lifestyledetails',
            name='diet_preferences',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan'), ('Diabetic Diet', 'Diabetic Diet')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
