# Generated by Django 5.1.6 on 2025-02-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0008_alter_lifestyledetails_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='current_prescriptions',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='current_prescriptions_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_proof_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lifestyledetails',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lifestyledetails',
            name='diet_preferences',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.PositiveIntegerField(help_text='Weight in kg'),
        ),
    ]
