# Generated by Django 5.1.6 on 2025-02-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0009_remove_medicalhistory_current_prescriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
