# Generated by Django 5.1.6 on 2025-02-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0010_alter_patient_height_alter_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='user_onboarding.patient'),
        ),
    ]
