# Generated by Django 4.2.3 on 2025-02-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0013_rename_emergencycontact_emergencycontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=10)),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='user_onboarding.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatusOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_message', models.CharField(default='Your health metrics are within normal range', max_length=255)),
                ('next_checkup_date', models.DateField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status_overview', to='user_onboarding.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_sugar', models.IntegerField(help_text='mg/dL')),
                ('ecg', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], max_length=20)),
                ('bmi', models.FloatField()),
                ('sleep_level', models.FloatField(help_text='Hours')),
                ('stress_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('blood_oxygen', models.IntegerField(help_text='Percentage')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='user_onboarding.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CheckupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_schedule', to='user_onboarding.patient')),
            ],
        ),
    ]
