# Generated by Django 5.1.6 on 2025-02-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0014_vitalsigns_healthstatusoverview_healthmetrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetrics',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
