# Generated by Django 5.1.6 on 2025-02-22 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0015_alter_healthmetrics_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admin',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='care_manager',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'CARE_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='kin',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'USER_KIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kin_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_location_status',
            field=models.CharField(blank=True, choices=[('AtHome', 'At Home'), ('Travelling', 'Travelling')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='usual_wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_registered', models.PositiveIntegerField(default=0)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='community_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=100)),
                ('prescribed_by', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('stock_remaining', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('current', 'Current'), ('completed', 'Completed')], default='current', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('care_manager', 'Care Manager'), ('buddy', 'Buddy'), ('doctor', 'Doctor')], max_length=20)),
                ('scheduled_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('gmeet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='user_onboarding.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=10)),
                ('remark', models.CharField(blank=True, choices=[('ESCALATED_TO_ADMIN', 'Escalated to Admin'), ('ESCALATED_TO_CARE_TEAM', 'Escalated to Care Team'), ('ESCALATED_TO_KIN', 'Escalated to Kin')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('date_initiated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('service_name', models.CharField(max_length=100)),
                ('current_work', models.CharField(max_length=200)),
                ('user_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user_initiated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
