# Generated by Django 5.1.6 on 2025-02-23 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0016_patient_admin_patient_care_manager_patient_kin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
