# Generated by Django 5.1.6 on 2025-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0018_labreport_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='LR_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Presc_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
