# Generated by Django 4.2.3 on 2025-02-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
