# Generated by Django 4.2.3 on 2025-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_proof',
            field=models.FileField(null=True, upload_to='id_proofs/'),
        ),
    ]
